// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: bydb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ByDbClient is the client API for ByDb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ByDbClient interface {
	Crud(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	Hello(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Greeting, error)
}

type byDbClient struct {
	cc grpc.ClientConnInterface
}

func NewByDbClient(cc grpc.ClientConnInterface) ByDbClient {
	return &byDbClient{cc}
}

func (c *byDbClient) Crud(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/bydb.ByDb/Crud", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byDbClient) Hello(ctx context.Context, in *Greeting, opts ...grpc.CallOption) (*Greeting, error) {
	out := new(Greeting)
	err := c.cc.Invoke(ctx, "/bydb.ByDb/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ByDbServer is the server API for ByDb service.
// All implementations must embed UnimplementedByDbServer
// for forward compatibility
type ByDbServer interface {
	Crud(context.Context, *Command) (*Response, error)
	Hello(context.Context, *Greeting) (*Greeting, error)
	mustEmbedUnimplementedByDbServer()
}

// UnimplementedByDbServer must be embedded to have forward compatible implementations.
type UnimplementedByDbServer struct {
}

func (UnimplementedByDbServer) Crud(context.Context, *Command) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Crud not implemented")
}
func (UnimplementedByDbServer) Hello(context.Context, *Greeting) (*Greeting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedByDbServer) mustEmbedUnimplementedByDbServer() {}

// UnsafeByDbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ByDbServer will
// result in compilation errors.
type UnsafeByDbServer interface {
	mustEmbedUnimplementedByDbServer()
}

func RegisterByDbServer(s grpc.ServiceRegistrar, srv ByDbServer) {
	s.RegisterService(&ByDb_ServiceDesc, srv)
}

func _ByDb_Crud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByDbServer).Crud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bydb.ByDb/Crud",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByDbServer).Crud(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _ByDb_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Greeting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByDbServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bydb.ByDb/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByDbServer).Hello(ctx, req.(*Greeting))
	}
	return interceptor(ctx, in, info, handler)
}

// ByDb_ServiceDesc is the grpc.ServiceDesc for ByDb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ByDb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bydb.ByDb",
	HandlerType: (*ByDbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Crud",
			Handler:    _ByDb_Crud_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _ByDb_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bydb.proto",
}
